using System.Text.RegularExpressions;

namespace ZZZCatchNPC
{
	public static class RandomMethod
	{
		public static string getDustConstName(int num)
		{
			return num switch
			{
				0 => "Dirt", 
				1 => "Stone", 
				2 => "Grass", 
				3 => "GrassBlades", 
				5 => "Blood", 
				6 => "Fire", 
				8 => "Iron", 
				9 => "Copper", 
				10 => "Gold", 
				11 => "Silver", 
				27 => "Shadowflame", 
				30 => "Web", 
				31 => "Smoke", 
				66 => "Rainbow", 
				68 => "BlueCrystalShard", 
				69 => "PinkCrystalShard", 
				70 => "PurpleCrystalShard", 
				80 => "Ice", 
				81 => "Tin", 
				82 => "Lead", 
				83 => "Tungsten", 
				84 => "Platinum", 
				139 => "Confetti", 
				219 => "Fireworks", 
				226 => "Electric", 
				228 => "GoldFlame", 
				229 => "Vortex", 
				236 => "Marble", 
				237 => "Mothron", 
				238 => "MothronEgg", 
				239 => "Silk", 
				240 => "Granite", 
				241 => "MarblePot", 
				242 => "PinkFlame", 
				243 => "PinkSlime", 
				244 => "CopperCoin", 
				245 => "SilverCoin", 
				246 => "GoldCoin", 
				247 => "PlatinumCoin", 
				248 => "EnchantedNightcrawler", 
				249 => "Grubby", 
				250 => "Sluggy", 
				251 => "Buggy", 
				254 => "CrystalPulse", 
				255 => "CrystalPulse2", 
				256 => "ToxicBubble", 
				257 => "BubbleBlock", 
				258 => "LavaMoss", 
				259 => "SolarFlare", 
				260 => "SparksMech", 
				261 => "AncientLight", 
				262 => "AmberBolt", 
				263 => "PortalBolt", 
				264 => "PortalBoltTrail", 
				265 => "LunarOre", 
				266 => "SomethingRed", 
				267 => "RainbowMk2", 
				268 => "Sandstorm", 
				269 => "Sandnado", 
				270 => "FlameBurst", 
				271 => "HealingPlus", 
				272 => "WitherLightning", 
				273 => "GreenBlood", 
				274 => "ApprenticeStorm", 
				275 => "Count", 
				214 => "BorealWood", 
				4 => "Slime", 
				_ => num switch
				{
					8 => "SteampunkMetal", 
					78 => "LivingWood", 
					147 => "Honey", 
					40 => "Cactus", 
					226 => "Martian", 
					23 => "Meteor", 
					240 => "Granite", 
					236 => "Marble", 
					68 => "Crystal", 
					10 => "Golden", 
					_ => num switch
					{
						78 => "PearlWood", 
						148 => "Lihzahrd", 
						5 => "Flesh", 
						80 => "Frozen", 
						3 => "Grass_Small", 
						12 => "HeartCrystal", 
						13 => "Glass", 
						14 => "Demonite", 
						_ => num switch
						{
							14 => "Corruption", 
							15 => "MagicMirror", 
							16 => "Cloud", 
							17 => "Corruption_Gravity", 
							18 => "Vile", 
							19 => "Sunflower", 
							20 => "PurificationPowder", 
							21 => "VilePowder", 
							22 => "Pot", 
							23 => "PiggyBank", 
							_ => num switch
							{
								23 => "Meteorite", 
								24 => "CorruptionThorns", 
								25 => "MeteorHead", 
								26 => "Bone", 
								27 => "GoblinSorcerer", 
								28 => "Clay", 
								29 => "DungeonWater_Old", 
								32 => "Sand", 
								33 => "Water", 
								34 => "BreatheBubble", 
								35 => "LavaBubbles", 
								36 => "Ash", 
								37 => "Obsidian", 
								38 => "Mud", 
								39 => "JungleGrass", 
								40 => "JungleGrass_Small", 
								41 => "GlowingMushroom", 
								42 => "Harpy", 
								43 => "Sparkle", 
								44 => "JungleSpore", 
								45 => "ManaRegeneration", 
								46 => "Poisoned", 
								47 => "HallowedGrass", 
								48 => "Cobalt", 
								49 => "Mythril", 
								50 => "Adamantine", 
								51 => "SnowBlock", 
								_ => num switch
								{
									51 => "Pearlsand", 
									52 => "UnholyWater", 
									53 => "Silt", 
									54 => "Wraith", 
									55 => "Pixie", 
									56 => "BlueFairy", 
									57 => "Enchanted_Gold", 
									_ => num switch
									{
										57 => "HallowedWeapons", 
										58 => "Enchanted_Pink", 
										59 => "BlueTorch", 
										60 => "RedTorch", 
										61 => "GreenTorch", 
										62 => "PurpleTorch", 
										63 => "WhiteTorch", 
										64 => "YellowTorch", 
										65 => "DemonTorch", 
										66 => "RainbowRod", 
										67 => "IceRod", 
										71 => "UndergroundHallowedEnemies", 
										72 => "Gastropod", 
										73 => "PinkFairy", 
										74 => "GreenFairy", 
										75 => "CursedTorch", 
										76 => "Snow", 
										77 => "Ebonwood", 
										78 => "RichMahogany", 
										79 => "Pearlwood", 
										85 => "UnusedBrown", 
										86 => "AmethystBolt", 
										87 => "TopazBolt", 
										88 => "SapphireBolt", 
										89 => "EmeraldBolt", 
										90 => "RubyBolt", 
										91 => "DiamondBolt", 
										92 => "Frost", 
										_ => num switch
										{
											92 => "FrostStaff", 
											93 => "Moss_Green", 
											94 => "Moss_Yellow", 
											95 => "Moss_Red", 
											96 => "Moss_Blue", 
											97 => "Moss_Purple", 
											98 => "Water_Corruption", 
											99 => "Water_Jungle", 
											100 => "Water_Hallowed", 
											101 => "Water_Snow", 
											102 => "Water_Desert", 
											103 => "Water_Space", 
											_ => num switch
											{
												103 => "Water_GlowingMushroom", 
												104 => "Water_Cavern", 
												105 => "Water_BloodMoon", 
												106 => "RuneWizard", 
												107 => "TerraBlade", 
												108 => "RainCloud", 
												109 => "Asphalt", 
												110 => "Clentaminator_Green", 
												111 => "Clentaminator_Cyan", 
												112 => "Clentaminator_Purple", 
												113 => "Clentaminator_Blue", 
												114 => "Clentaminator_Red", 
												115 => "CrimtaneWeapons", 
												116 => "Skyware", 
												117 => "Crimstone", 
												118 => "Ice_Purple", 
												119 => "Ice_Pink", 
												120 => "Ice_Red", 
												121 => "Shadewood_Tree", 
												122 => "BorealWood", 
												123 => "Water_Crimson", 
												124 => "SandstormInABottle", 
												125 => "CrimsonGrass", 
												126 => "Shadewood", 
												127 => "Flare", 
												128 => "Chlorophyte", 
												129 => "Rope", 
												130 => "Firework_Red", 
												131 => "Firework_Green", 
												132 => "Firework_Blue", 
												133 => "Firework_Yellow", 
												134 => "Firework_Pink", 
												135 => "IceTorch", 
												136 => "Crimslime", 
												137 => "IcyMerman", 
												138 => "Amber", 
												139 => "Confetti_Blue", 
												140 => "Confetti_Green", 
												141 => "Confetti_Pink", 
												142 => "Confetti_Yellow", 
												143 => "Paint", 
												144 => "Palladium", 
												145 => "Orichalcum", 
												146 => "Titanium", 
												147 => "Hive", 
												148 => "Lihzahrd", 
												149 => "Slush", 
												150 => "Bee", 
												151 => "SeaSnail", 
												_ => num switch
												{
													151 => "Squid", 
													152 => "HoneyBubbles", 
													153 => "Honey", 
													154 => "Rain", 
													155 => "AmbienDarkBrown", 
													156 => "Ultrabright", 
													157 => "ChlorophyteWeapon", 
													158 => "OrangeTorch", 
													159 => "Teleporter", 
													160 => "MagnetSphere", 
													161 => "IceGolem", 
													162 => "HeatRay", 
													163 => "PoisonStaff", 
													_ => num switch
													{
														163 => "DryadsWard", 
														164 => "TeleportationPotion", 
														165 => "FungiHit", 
														166 => "Plantera_Pink", 
														167 => "Plantera_Green", 
														168 => "PlanteraBulb", 
														169 => "IchorTorch", 
														170 => "Ichor", 
														171 => "Venom", 
														172 => "DungeonWater", 
														173 => "ShadowbeamStaff", 
														174 => "InfernoFork", 
														175 => "SpectreStaff", 
														176 => "BubbleBursBlue", 
														177 => "BubbleBursPink", 
														178 => "BubbleBursGreen", 
														179 => "BubbleBursPurple", 
														180 => "DungeonSpirit", 
														181 => "GiantCursedSkullBolt", 
														182 => "TheDestoryer", 
														183 => "VampireHeal", 
														184 => "ScourgeOfTheCorruptor", 
														185 => "FrostHydra", 
														186 => "RedsWingsRun", 
														187 => "Flare_Blue", 
														188 => "FartInAJar", 
														189 => "Pumpkin", 
														190 => "Hay", 
														191 => "SpookyWood", 
														192 => "Ghost", 
														_ => num switch
														{
															192 => "BunnySlime", 
															193 => "SlimeBunny", 
															194 => "Scarecrow", 
															195 => "BatScepter", 
															196 => "Everscream", 
															197 => "NorthPole", 
															198 => "Firefly", 
															199 => "Butterfly", 
															200 => "Worm", 
															201 => "Snail", 
															202 => "GlowingSnail", 
															203 => "Scorpion", 
															204 => "TreasureSparkle", 
															_ => num switch
															{
																204 => "SpelunkerGlowstickSparkle", 
																205 => "VenomStaff", 
																206 => "UnusedWhiteBluePurple", 
																207 => "DynastyWood", 
																208 => "DynastyShingle_Red", 
																209 => "DynastyShingle_Blue", 
																210 => "DynastyWall", 
																211 => "Wet", 
																212 => "BubbleBursWhite", 
																213 => "MinecartSpark", 
																214 => "BorealWood_Small", 
																215 => "PalmWood", 
																216 => "PirateStaff", 
																217 => "FishronWings", 
																_ => num switch
																{
																	217 => "RazorbladeTyphoon", 
																	218 => "Rain_BloodMoon", 
																	219 => "FireworkFountain_Red", 
																	220 => "FireworkFountain_Green", 
																	221 => "FireworkFountain_Blue", 
																	222 => "FireworkFountain_Yellow", 
																	223 => "FireworkFountain_Pink", 
																	224 => "Shiverthorn", 
																	225 => "Coralstone", 
																	227 => "MartianHit", 
																	228 => "MartianSaucerSpark", 
																	229 => "InfluxWaver", 
																	_ => num switch
																	{
																		229 => "Phantasmal", 
																		230 => "DrillContainmentUnit", 
																		_ => num switch
																		{
																			230 => "CosmicCarKeys", 
																			231 => "ViciousPowder", 
																			232 => "GoldCritter", 
																			233 => "GoldCritter_LessOutline", 
																			234 => "BoneTorch", 
																			235 => "LifeDrain", 
																			242 => "PinkTorch", 
																			252 => "FrostDaggerfish", 
																			253 => "TsunamiInABottle", 
																			_ => num switch
																			{
																				253 => "SailfishBoots", 
																				254 => "CrystalSerpent", 
																				255 => "CrystalSerpenPink", 
																				256 => "Toxikarp", 
																				260 => "MechanicalCart", 
																				266 => "BloodWater", 
																				267 => "LastPrism", 
																				_ => "Unknown", 
																			}, 
																		}, 
																	}, 
																}, 
															}, 
														}, 
													}, 
												}, 
											}, 
										}, 
									}, 
								}, 
							}, 
						}, 
					}, 
				}, 
			};
		}

		public static string GetDustName(int num)
		{
			return Regex.Replace(getDustConstName(num), "([A-Z])", " $1").Trim().Replace("_", " ");
		}
	}
}
